# Generated by Django 3.1.7 on 2021-03-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('workout_type', models.CharField(max_length=25)),
                ('workout_length', models.IntegerField()),
                ('calories_burned', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('date', models.DateField(verbose_name='workout date')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('a', 'run'), ('b', 'ride'), ('c', 'walk')], default='a', max_length=50)),
            ],
        ),
    ]
