# Generated by Django 3.1.7 on 2021-03-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210317_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutType',
        ),
    ]
