# Generated by Django 3.1.7 on 2021-03-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_workouttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('run', 'run'), ('ride', 'ride'), ('walk', 'walk'), ('hike', 'hike'), ('canoe', 'canoe'), ('weight training', 'weight training'), ('swim', 'swim'), ('cross-fit', 'cross-fit'), ('stairs-stepper', 'stairs-stepper'), ('elliptical', 'elliptical'), ('workout - other', 'workout - other')], default='run', max_length=50),
        ),
    ]
